fn main() {
    let dist_dir = std::path::Path::new("../python-sidecar/dist");
    let bundled_sidecar = if cfg!(target_os = "windows") {
        dist_dir.join("sidecar.exe")
    } else {
        dist_dir.join("sidecar")
    };

    if !bundled_sidecar.exists() {
        let placeholder = dist_dir.join("sidecar-placeholder.txt");
        if let Err(err) = std::fs::create_dir_all(dist_dir) {
            panic!("failed to create sidecar dist directory: {}", err);
        }
        if let Err(err) = std::fs::write(
            &placeholder,
            "Bundled sidecar binary will be generated by npm run build:release.\n",
        ) {
            panic!("failed to create sidecar placeholder: {}", err);
        }
    }

    tauri_build::build()
}
